### ISSUE TITLE
此版本兼容上传视频吗

### ISSUE THREAD

**Issue by popfaker** [jonexyz/wang-editor-v4#1]
您好，感谢提供的wang-editor-v4的插件。
我现在在kindeditor和wangeditor之间徘徊，个人比较偏向wangEditor。但是目前使用的wangeditorV3版本，该版本是不支持上传本地视频的。由于需求的问题，被迫放弃。
我查看文档发现wang-editor的v4.6.3 开始支持上传视频了
此插件兼容视频吗？

**Comment by jonexyz** [comment]
当前版本用的是 wangeditor-4.7.5 版本 是支持上传 视频的。

官方文档地址 https://www.wangeditor.com/doc/

刚本地测试了一下，按照文档在 admin.php 中添加视频上传相关的配置，并完善接口，就可以上传视频了

配置demo如下，视频上传接口自行按照文档编写即可
```
'config' => [
                'default'=>[
                    'uploadImgServer' => '/admin/upload_img',  //配置上传接口
                    'uploadImgMaxSize' => 3 * 1024 * 1024, // 将图片大小限制为 3M
                    'uploadFileName' => 'images[]', //定义上传的filename，即上传图片的名称
                    'height'=>500 ,

                    // 视频上传相关
                    'uploadVideoServer' => '/api/upload-video',
                    'uploadVideoAccept' => ['mp4'],
                    'uploadVideoMaxSize' => 100 * 1024 * 1024 ,
                    'uploadVideoName' => 'video'
                ],
            ]
```

**Comment by popfaker** [comment]
> 当前版本用的是 wangeditor-4.7.5 版本 是支持上传 视频的。
> 
> 官方文档地址 https://www.wangeditor.com/doc/
> 
> 刚本地测试了一下，按照文档在 admin.php 中添加视频上传相关的配置，并完善接口，就可以上传视频了
> 
> 配置demo如下，视频上传接口自行按照文档编写即可
> 
> ```
> 'config' => [
>                 'default'=>[
>                     'uploadImgServer' => '/admin/upload_img',  //配置上传接口
>                     'uploadImgMaxSize' => 3 * 1024 * 1024, // 将图片大小限制为 3M
>                     'uploadFileName' => 'images[]', //定义上传的filename，即上传图片的名称
>                     'height'=>500 ,
> 
>                     // 视频上传相关
>                     'uploadVideoServer' => '/api/upload-video',
>                     'uploadVideoAccept' => ['mp4'],
>                     'uploadVideoMaxSize' => 100 * 1024 * 1024 ,
>                     'uploadVideoName' => 'video'
>                 ],
>             ]
> ```
非常感谢
