### ISSUE TITLE
视频上传 csrf_token 问题

### ISSUE THREAD

**Issue by springjk** [jonexyz/wang-editor-v4#3]
我在使用中发现上传视频功能如果没有配置 csrf_token 是无法使用，无法过验证，错误码 419。

正常使用需要在下方添加

https://github.com/jonexyz/wang-editor-v4/blob/main/src/Editor.php#L45
```
editor.config.uploadVideoParams = {_token: '$token'}
```
本想 PR 可是看到了 #1 说是正常的，是我弄错了什么吗？

另，感谢你的项目，为我节约了时间。👍

**Comment by jonexyz** [comment]
看了一下代码，大概明白你说的问题所在了，这里应该是自定义的上传图片视频的接口限制的csrf限制。因为我自己在使用图片视频上传的时候是在csrf中间件中过滤掉了该路由的。

**Comment by springjk** [comment]
过滤掉始终不是一个稳妥的做法，能否在这里能否加上这行并更新 package 。

**Comment by jonexyz** [comment]
好的，我更新一下 package

**Comment by springjk** [comment]
已验证，期待你的 v5。💪🏻
